### ISSUE TITLE
Design the "search results" screen

### ISSUE THREAD

**Issue by mrtnzlml** [mrtnzlml/native#2]
Currently, we are not doing the whole order - just search results. Idea is to have one screen with results similar to Kiwi.com results and one detailed screen with all the information about the flight.

**Comment by MRTNKCR** [comment]
@mrtnzlml Do you have an actual design of the page? Can I be of any help with the design tasks?

**Comment by mrtnzlml** [comment]
Not now. We are just trying to move it to "not completely ugly" state. Future of this project is very unclear because we are going to integrate RN little bit differently into our applications...
