### ISSUE TITLE
Design "my bookings" after login

### ISSUE THREAD

**Issue by mrtnzlml** [mrtnzlml/native#5]
The homepage contains all the bookings (current and past) so let's make them nice... :)

All bookings are already with offline support.

**Comment by jakubzaba** [comment]
I'll take this one

**Comment by mrtnzlml** [comment]
Ok, I am reassigning this issue to me. It's taking too long.

**Comment by mrtnzlml** [comment]
Alright, GraphQL API fixed, but not merged yet. Waiting for:

- [ ] `chatbot/kiwi-chatbot-infrastructure!528`
- [ ] `chatbot/kiwi-chatbot-infrastructure!522`
