### ISSUE TITLE
Design detail of the booking

### ISSUE THREAD

**Issue by mrtnzlml** [mrtnzlml/native#6]
Let's show all the information about one booking (already should support offline).

**Comment by VaclavSir** [comment]
Can you assign this one to me plz?

**Comment by mrtnzlml** [comment]
Sure - link sent. Thanks.

**Comment by mrtnzlml** [comment]
Hi, this is the last issue from "Hackathon" sprint. Will you have time to work on it next week or should I take it and finish it?

**Comment by VaclavSir** [comment]
I think I will have some time on Thursday.

**Comment by VaclavSir** [comment]
I'm sorry but I didn't find the time yesterday and probably won't until the next week.

**Comment by mrtnzlml** [comment]
OK, no problem. I am reassigning this task to me so it's not stale for a long time and you can work on something later when you will have time (there is going to be a lot of work).

**Comment by mrtnzlml** [comment]
Solved. It's not very nice, but it's not super ugly and that's important now... :)
